# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

#pool:
#  vmImage: ubuntu-latest
parameters:
  - name: ProjectName
    displayName: Project Name
    type: string
    default: Project1
    values:
      - Project1
  - name: Shared Parameter
    displayName: Shared Parameter
    type: string
    default: shared-paramterValue1
    values:
      - shared-paramterValue1
      - shared-paramterValue2
      
stages:
- stage: build
  jobs:
    - job: build
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
- stage: test
  jobs:
    - job: test
      steps:
      - script: echo Test world!
        displayName: 'Run a Test one-line script'
